$(document).ready(function(){

    definitions = {
        "CIM":       "City Infrastructure Management|CIM is an umbrella concept that encompasses hardware, software and application components from Cisco and an ecosystem of partners to provide support for city agency activities as well as for citizen, tourism and business activities. It includes a growing portfolio of solutions to address the challenges urban leaders face today, including:<ul><li>Smart+Connected City Wi-Fi</li><li>Smart+Connected City Parking</li><li>Smart+Connected City Traffic</li><li>Smart+Connected City Safety and Security</li><li>Remote Expert Smart Solution for Government Services</li></ul>|http://blogs.cisco.com/government/smartconnectedcity-series-city-infrastructure-management-city-wi-fi-and-a-global-urban-services-revolution",
        "S+CC":      "Smart+Connected Cities|The Smart+Connected City solution portfolio includes remote access to government services as well as City Infrastructure Management solutions for connected parking, traffic, and safety and security.",
        "CCS":       "Cisco Cloud Services|Cisco and our partners are connecting private, public, open, and hybrid clouds with the globally connected network of clouds, the Intercloud.<br>Unlike other hybrid approaches, our cloud strategy allows for workload portability across the entire Intercloud. An open, standards-based global infrastructure makes this possible. We can help you overcome the security, regulatory, and compliance issues you're facing with existing public and hybrid cloud solutions.<br>Our approach gives you the choice of hundreds of enterprise-class cloud services with the compliance and control you need:<ul><li>Private and Hybrid Clouds</li><li>Clouds from Cisco Powered Providers</li><li>Cloud Professional Services</li><li>Cloud Consumption Services</li><li>Managed Cloud Services</li><li>Cisco OpenStack Solutions</li><li>For Cloud Providers: Building a Public Cloud</li></ul>|http://www.cisco.com/web/solutions/trends/cloud/index.html",
        "CMX":       "Cisco Connected Mobile Experiences|Whether you are in retail, hospitality, transportation, healthcare, education, or government, visitors to your venue are always on, always connected. Cisco Connected Mobile Experiences (CMX) lets you tap into this connected lifestyle and provide relevant mobile content while gaining meaningful analytics.Our professional services team can help you define and deliver the Connected Mobile Experiences to back your business initiatives. This solution, for example, counts the number of smartphones and tablets in different areas to create color-coded maps. City planners use the location information to plan development and transportation.|http://www.cisco.com/c/en/us/solutions/enterprise-networks/connected-mobile-experiences/index.html?vs_f=Products+Launch+RSS+Feeds&vs_p=Cisco+Connected+Mobile+Experiences+Boost+Revenues+with+Better+Service&vs_k=1",
        "SXP":       "Service Exchange Platform|The Service Exchange Platform (SXP) provides a comprehensive cloud solution for delivering business process and automation as a service in both Enterprise <div class='inlink'>B2B</div> and Marketplace Exchange settings. SXP rapidly connects users, applications, and data to form a highly secure enterprise-grade cloud that delivers business services faster, at lower cost, and at scale.|http://www.cisco.com/c/en/us/products/cloud-systems-management/service-exchange-platform/index.html",
        "IDM":       "Identity Management|Cisco offers a cloud-based identity and access management solution, automating the process of securing and managing digital identities.<ul><li>Manage access to applications and information for customers, partners, and suppliers</li><li>Rapidly and dynamically connect identity systems from inside and outside the enterprise</li><li>Provide extended single sign-on for any user on any device for any application or data service</li><li>Support billions of security transactions per year (SOC-2 rated and engineered)</li></ul>|http://www.cisco.com/c/en/us/products/cloud-systems-management/service-exchange-platform/index.html",
        "ACI":       "Application Centric Infrastructure|Cisco Application-Centric Infrastructure (ACI) reduces <div class='inlink'>TCO</div> (Total Cost of Ownership), automates IT tasks, and accelerates data center application deployments. It accomplishes this using a business-relevant Software Defined Networking (<div class='inlink'>SDN</div>) policy model across networks, servers, storage, security, and services.|http://www.cisco.com/c/en/us/solutions/data-center-virtualization/application-centric-infrastructure/index.html",
        "EMSP":      "Enterprise Mobility Services Platform|Supports the development of business-relevant mobile applications. Based on a mobile application ecosystem, it supports backend data integration, mobile application management, and application development. EMSP can be deployed on the premises or hosted in the cloud. EMSP helps you:<ul><li>Use real-time data to monetize and influence customer behavior</li><li>Integrate your business applications and enterprise systems to create enterprise class mobile applications</li><li>Make mobility more secure with location and identity-based access integrated into the mobile applications</li></ul>|http://www.cisco.com/c/en/us/products/wireless/enterprise-mobility-services-platform/index.html",
        "SDN":       "Software Defined Networking|Software Defined Networking (SDN) is enabling organizations to accelerate application deployment and delivery, dramatically reducing <div class='inlink'>IT</div> costs through policy-enabled workflow automation. SDN technology enables cloud architectures by delivering automated, on-demand application delivery and mobility at scale. SDN enhances the benefits of data center virtualization, increasing resource flexibility and utilization and reducing infrastructure costs and overhead.<br>SDN accomplishes these business objectives by converging the management of network and application services into centralized, extensible orchestration platforms that can automate the provisioning and configuration of the entire infrastructure. Common centralized IT policies bring together disparate IT groups and workflows. The result is a modern infrastructure that can deliver new applications and services in minutes, rather than days or weeks required in the past.<br>SDN delivers speed and agility when deploying new applications and business services. Flexibility, policy, and programmability are the hallmarks of Cisco's SDN solutions, with a platform capable of handling the most demanding networking need of today and tomorrow.|http://www.cisco.com/web/solutions/trends/sdn/index.html",
        "TCO":       "Total Cost of Ownership|A financial estimate intended to help buyers and owners determine the direct and indirect costs of a product or system. It is a management accounting concept that can be used in full cost accounting or even ecological economics where it includes social costs.|http://en.wikipedia.org/wiki/Total_cost_of_ownership|Wiki",
        "NFV":       "Network Functions Virtualization|A network architecture concept that proposes using IT virtualization related technologies to virtualize entire classes of network node functions into building blocks that may be connected, or chained, to create communication services.<br>NFV relies upon, but differs from, traditional server virtualization techniques such as those used in enterprise IT. A virtualized network function, or VNF, may consist of one or more virtual machines running different software and processes, on top of industry standard high volume servers, switches and storage, or even cloud computing infrastructure, instead of having custom hardware appliances for each network function.<br>For example, a virtualized session border controller function could be deployed to protect a network without the typical cost and complexity of obtaining and installing physical units. Other examples of NFV include virtualized load balancers, firewalls, intrusion detection devices and WAN accelerators.|http://en.wikipedia.org/wiki/Network_functions_virtualization|Wiki",
        "IOx":       "Combination of Cisco IOS and Linux|Cisco IOx brings together Cisco <div class='inlink'>IOS</div>, the industry-leading networking operating system, and Linux, the leading open source platform. Because Linux-based applications can run on Cisco devices in the Cisco IOx framework, businesses can bring their own applications and interfaces to the network. Cisco IOx offers developers a way to create IoT applications such as data aggregation, control systems, and access control and have them run on edge network devices. Businesses in manufacturing, transportation, energy, and beyond can now harness the value in the Internet of Things.|https://developer.cisco.com/site/iox/technical-overview/",
        "IOS":       "Internetwork Operating System|Cisco IOS (originally Internetwork Operating System) is software used on most Cisco Systems routers and current Cisco network switches. (Earlier switches ran CatOS.) IOS is a package of routing, switching, internetworking and telecommunications functions integrated into a multitasking operating system.|http://en.wikipedia.org/wiki/Cisco_IOS|Wiki",
        "BDM":       "Business Development Model|A detailed plan that defines how company resources will be used to create sales and revenue. This model is a guide for the strategy and growth of a business. The model will change over time based on new market trends and business demand.<br>The business model is a plan for running a company. It is important to build this plan based on strategies known to work. Using an existing model for a specific type of company provides a good starting point for the owners of company.<br>When creating a business plan, it is important to define a strategy that can generate income and growth. This typically includes techniques for lead generation, prospect definition, customer management, and customer retention polices. This business development model becomes the blueprint for how an organization interacts with clients and adds new clients.<br>There are many types of business development models available today. These models are sample business plans that an entrepreneur can use as a starting point for creating his specific plan for the company. The business model is typically specific to a particular business field. Some examples include construction, manufacturing, consulting, and software development.|http://www.wisegeek.com/what-is-a-business-development-model.htm",
        "NERV":      "Network Emergency Response Vehicle|The Cisco Network Emergency Response Vehicle (NERV) is a mobile communication center that is designed to establish interoperable communications in emergency situations. The NERV is supported by Cisco Tactical Operations, a highly skilled and dedicated team that can mobilize and respond to natural disasters and other catastrophes when normal communications infrastructure have been degraded or destroyed.<br>The Cisco NERV is a command and communications resource for first responders, critical infrastructure, and other organizations that have been affected by a catastrophic event and require mission-critical networking to recover normal operations. It exceeds the National Incident Management System (NIMS) standards for Type II Mobile Communication Centers. The Cisco NERV, along with its NIMS certified team, helps organizations by:<ul><li>Arriving for disaster response missions ready for up to 4 days of continuous operations without impacting already challenged resources.</li><li>Operating seamlessly with police, fire, emergency medical services, National Guard, and other responders within an incident command system or unified command structure.</li><li>Receiving 24-hour, proactive intelligence and logistical support from the Cisco Security Facilities Operations Centers (SFOC).</li></ul>The Cisco NERV and Tactical Operations team have been deployed in support of a variety of incidents, including hurricanes, tornadoes, floods, earthquakes, wildfires and man-made disasters.|http://www.cisco.com/web/strategy/docs/gov/NERV_AAG.pdf",
        "MSE":       "Cisco Mobility Services Engine|A platform that helps organizations increase visibility into the network, customize location-based mobile services, and strengthen security. Cisco Mobility Services Engine supports mobility services software in a modular fashion, with various solutions delivered through applications.|http://www.cisco.com/c/en/us/products/wireless/mobility-services-engine/index.html",
        "BaaS":      "Business (Analytics) as a Service|Enabling contextual correlations between domains",
        "DaaS":      "Domain as a Service|Normalizing data across domains and delivering \"as-a-service\"",
        "TaaS":      "Things as a Service|Data from sensors, within one domain, delivered as-a-service",
        "RFP":       "Request for Proposal|A solicitation, often made through a bidding process, by an agency or company interested in procurement of a commodity, service or valuable asset, to potential suppliers to submit business proposals. It is submitted early in the procurement cycle, either at the preliminary study, or procurement stage.<br>The RFP presents preliminary requirements for the commodity or service, and may dictate to varying degrees the exact structure and format of the supplier's response. Effective RFPs typically reflect the strategy and short/long-term business objectives, providing detailed insight upon which suppliers will be able to offer a matching perspective.<br>Similar requests include a request for quotation and a request for information.<br>In principle, an RFP:<ul><li>informs suppliers that an organization is looking to procure and encourages them to make their best effort.</li><li>requires the company to specify what it proposes to purchase. If the requirements analysis has been prepared properly, it can be incorporated quite easily into the Request document.</li><li>alerts suppliers that the selection process is competitive.</li><li>allows for wide distribution and response.</li><li>ensures that suppliers respond factually to the identified requirements.</li><li>is generally expected to follow a structured evaluation and selection procedure, so that an organization can demonstrate impartiality - a crucial factor in public sector procurements.</li></ul>Basically asking \"How much does this cost?\"|http://en.wikipedia.org/wiki/Request_for_proposal|Wiki",
        "CCW":       "Cisco Commerce Workspace|A single end-to-end workspace for all business transactions. Register deals, quote, configure, price, and order Cisco products, software, and services.|http://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/prime-infrastructure/guide-c07-731621.html",
        "Devnet":    "Developer Network|A network of developers, like Apple's Developer program for apps.",
        "SSID":      "Service Set Identifier|Unique identifier for a wireless <div class='inlink'>LAN</div>.|http://www.webopedia.com/TERM/S/SSID.html",
        "LAN":       "Local Area Network|A computer network that interconnects computers within a limited area such as a home, school, computer laboratory, or office building, using network media.|http://en.wikipedia.org/wiki/Local_area_network|Wiki",
        "CCTV":      "Closed Circuit Television|The use of video cameras to transmit a signal to a specific place, on a limited set of monitors. It differs from broadcast television in that the signal is not openly transmitted, though it may employ point to point (P2P), point to multipoint, or mesh wireless links.|http://en.wikipedia.org/wiki/Closed-circuit_television|Wiki",
        "API":       "Application Program Interface|A set of routines, protocols, and tools for building software applications. The API specifies how software components should interact and APIs are used when programming graphical user interface (GUI) components.|http://en.wikipedia.org/wiki/Application_programming_interface|Wiki",
        "GW":        "Gateway|In telecommunications, the term gateway has the following meaning:<ul><li>In a communications network, a network node equipped for interfacing with another network that uses different protocols.<ul><li>A gateway may contain devices such as protocol translators, impedance matching devices, rate converters, fault isolators, or signal translators as necessary to provide system interoperability. It also requires the establishment of mutually acceptable administrative procedures between both networks.</li><li>A protocol translation/mapping gateway interconnects networks with different network protocol technologies by performing the required protocol conversions.</li></ul><li>Loosely, a computer or computer program configured to perform the tasks of a gateway. For a specific case, see default gateway.</li></ul>Gateways, also called protocol converters, can operate at any network layer. The activities of a gateway are more complex than that of the router or switch as it communicates using more than one protocol.<br>Both the computers of Internet users and the computers that serve pages to users are host nodes, while the nodes that connect the networks in between are gateways. For example, the computers that control traffic between company networks or the computers used by internet service providers (ISPs) to connect users to the internet are gateway nodes.<br>In the network for an enterprise, a computer server acting as a gateway node is often also acting as a proxy server and a firewall server. A gateway is often associated with both a router, which knows where to direct a given packet of data that arrives at the gateway, and a switch, which furnishes the actual path in and out of the gateway for a given packet.<br>On an IP network, clients should automatically send IP packets with a destination outside a given subnet mask to a network gateway. A subnet mask defines the IP range of a private network. For example, if a private network has a base IP address of 192.168.0.0 and has a subnet mask of 255.255.255.0, then any data going to an IP address outside of 192.168.0.X will be sent to that network's gateway. While forwarding an IP packet to another network, the gateway might or might not perform Network Address Translation.<br>A gateway is an essential feature of most routers, although other devices (such as any PC or server) can function as a gateway.|http://en.wikipedia.org/wiki/Gateway_(telecommunications)|Wiki",
        "PLC":       "Programmable Logic Controller|A digital computer used for automation of typically industrial electromechanical processes, such as control of machinery on factory assembly lines, amusement rides, or light fixtures. PLCs are used in many machines, in many industries. PLCs are designed for multiple arrangements of digital and analog inputs and outputs, extended temperature ranges, immunity to electrical noise, and resistance to vibration and impact. Programs to control machine operation are typically stored in battery-backed-up or non-volatile memory. A PLC is an example of a \"hard\" real-time system since output results must be produced in response to input conditions within a limited time, otherwise unintended operation will result.|http://en.wikipedia.org/wiki/Programmable_logic_controller|Wiki",
        "VSM":       "Video Surveillance Manager|Provides a web-based toolkit for configuration, management, display, and control of video from a wide variety of both Cisco and third-party surveillance endpoints. Uses IP technology to provide outstanding scalability in terms of sites, cameras, viewers, and storage. Delivers low-latency, high-quality, event-tagged video. Supports a broad range of network topologies and platforms ranging from virtual to non-virtual, centralized to decentralized, and everything in between. Enables simple, effective management through comprehensive templating capability.|http://www.cisco.com/c/en/us/products/physical-security/video-surveillance-manager/index.html",
        "ISV":       "Independent Software Vendor|An organization specializing in making or selling software, designed for mass or niche markets. This is in contrast to software developed for in-house use only within an organization or software designed or adapted for a single, specific customer.<br>ISVs software may be for any purpose. Example include software for real estate brokers, scheduling for healthcare personnel, barcode scanning, stock maintenance, gambling, retailing, energy exploration, vehicle fleet management, even child care management software.<br>An ISV makes and sells software products that run on one or more computer hardware or operating system platforms. Companies that make the platforms, such as Microsoft, Cisco, IBM, Hewlett-Packard, Novell, Google, Oracle, Apple, SAP, and salesforce.com encourage and lend support to ISVs, often with special \"business partner\" programs. These programs enable the platform provider and the ISV to leverage joint strengths and convert them into incremental business opportunities.|http://en.wikipedia.org/wiki/Independent_software_vendor|Wiki",
        "CBO":       "Connected Business Operations|People in small and medium-sized businesses (<div class='inlink'>SMBs</div>) regularly connect with others who are vital to their success. Customers bring income, the lifeblood of any business. Partners, such as contractors and suppliers, provide services and products for daily operations. Prospects are vital for growth and new opportunities. And employees are the brains, hands, eyes, and ears that make a business successful.|http://www.cisco.com/cisco/web/solutions/small_business/resource_center/articles/connect_employees_and_offices/networking101/index.html",
        "IPICS":     "Cisco IP Interoperability and Collaboration System|A comprehensive IP-based dispatch and incidence response solution.",
        "SCK":       "Smart Citizen Kit|Data-processing board: Arduino compatible, solar panel charger. Measures temperature, humidity, CO, NO2, light, sound",
        "PBR":       "Policy-Based Routing|In computer networking, policy-based routing (PBR) is a technique used to make routing decisions based on policies set by the network administrator.<br>When a router receives a packet it normally decides where to forward it based on the destination address in the packet, which is then used to look up an entry in a routing table. However, in some cases, there may be a need to forward the packet based on other criteria. For example, a network administrator might want to forward a packet based on the source address, not the destination address. This should not be confused with source routing.<br>Policy-based routing may also be based on the size of the packet, the protocol of the payload, or other information available in a packet header or payload. This permits routing of packets originating from different sources to different networks even when the destinations are the same and can be useful when interconnecting several private networks.<br>In the Cisco <div class='inlink'>IOS</div>, PBR is implemented using route maps. Linux supports multiple routing tables since version 2.2.|http://en.wikipedia.org/wiki/Policy-based_routing|Wiki",
        "EAP":       "Extensible Authentication Protocol|An authentication framework frequently used in wireless networks and point-to-point connections. It provides for the transport and usage of keying material and parameters generated by EAP methods. There are many methods defined by RFCs and a number of vendor specific methods and new proposals exist. EAP is not a wire protocol; instead it only defines message formats. Each protocol that uses EAP defines a way to encapsulate EAP messages within that protocol's messages.|http://en.wikipedia.org/wiki/Extensible_Authentication_Protocol|Wiki",
        "EAP-FAST":  "Extensible Authentication Protocol-Flexible Authentication via Secure Tunneling|The EAP-FAST protocol is a new, publicly accessible IEEE 802.1X <div class='inlink'>EAP</div> type that Cisco developed to support customers that cannot enforce a strong password policy and want to deploy an 802.1X EAP type that does not require digital certificates.<br>The EAP-FAST protocol is a client-server security architecture that encrypts EAP transactions with a Transport Level Security (TLS) tunnel. EAP-FAST tunnel establishment is based on strong secrets that are unique to users. These strong secrets are called PACs, which the ACS generates by using a master key known only to the ACS.|http://www.cisco.com/c/en/us/support/docs/wireless/4400-series-wireless-lan-controllers/99791-eapfast-wlc-rad-config.html",
        "RFC":       "Request For Comments|A publication of the Internet Engineering Task Force (IETF) and the Internet Society, the principal technical development and standards-setting bodies for the Internet.<br>An RFC is authored by engineers and computer scientists in the form of a memorandum describing methods, behaviors, research, or innovations applicable to the working of the Internet and Internet-connected systems. It is submitted either for peer review or simply to convey new concepts, information, or (occasionally) engineering humor. The IETF adopts some of the proposals published as RFCs as Internet standards.|http://en.wikipedia.org/wiki/Request_for_Comments|Wiki",
        "SLA":       "Service Level Agreements|A service-level agreement (SLA) is a part of a service contract where a service is formally defined. Particular aspects of the service - scope, quality, responsibilities - are agreed between the service provider and the service user. A common feature of an SLA is a contracted delivery time (of the service or performance). As an example, Internet service providers and telephone companies will commonly include service level agreements within the terms of their contracts with customers to define the level(s) of service being sold in plain language terms. In this case the SLA will typically have a technical definition in terms of mean time between failures (MTBF), mean time to repair or mean time to recovery (MTTR); identifying which party is responsible for reporting faults or paying fees; responsibility for various data rates; throughput; jitter; or similar measurable details.|http://en.wikipedia.org/wiki/Service-level_agreement|Wiki",
        "SKU":       "Stock Keeping Unit|A store's or catalog's product and service identification code, often portrayed as a machine-readable bar code that helps the item to be tracked for inventory. A stock keeping unit (SKU) does not need to be assigned to physical products in inventory.|http://en.wikipedia.org/wiki/Stock_keeping_unit|Wiki",
        "EULA":      "End-User License Agreement|A contract between the manufacturer of computer software and the person who installs and uses it.|http://en.wikipedia.org/wiki/End-user_license_agreement|Wiki",
        "IaaS":      "Infrastructure as a Service|A type of cloud computing in which a third-party provider hosts virtualized computing resources over the Internet. IaaS is one of three main categories of cloud computing services, alongside Software as a Service (<div class='inlink'>SaaS</div>) and Platform as a Service (<div class='inlink'>PaaS</div>). In an IaaS model, a third-party provider hosts hardware, software, servers, storage and other infrastructure components on behalf of its users. IaaS providers also host users' applications and handle tasks including system maintenance, backup and resiliency planning.<br>IaaS platforms offer highly scalable resources that can be adjusted on-demand. This makes IaaS well-suited for workloads that are temporary, experimental or change unexpectedly.<br>Other characteristics of IaaS environments include the automation of administrative tasks, dynamic scaling, desktop virtualization and policy-based services.<br>IaaS customers pay on a per-use basis, typically by the hour, week or month. Some providers also charge customers based on the amount of virtual machine space they use. This pay-as-you-go model eliminates the capital expense of deploying in-house hardware and software. However, users should monitor their IaaS environments closely to avoid being charged for unauthorized services.|http://searchcloudcomputing.techtarget.com/definition/Infrastructure-as-a-Service-IaaS",
        "NPI":       "New Product Introduction|The process of how a new product is introduced.",
        "SaaS":      "Software as a Service|A software distribution model in which applications are hosted by a vendor or service provider and made available to customers over a network, typically the Internet. SaaS is becoming an increasingly prevalent delivery model as underlying technologies that support Web services and service-oriented architecture (SOA) mature and new developmental approaches, such as Ajax, become popular. Meanwhile, broadband service has become increasingly available to support user access from more areas around the world.<br>SaaS is closely related to the ASP (application service provider) and on demand computing software delivery models. IDC identifies two slightly different delivery models for SaaS. The hosted application management (hosted AM) model is similar to ASP: a provider hosts commercially available software for customers and delivers it over the Web. In the software on demand model, the provider gives customers network-based access to a single copy of an application created specifically for SaaS distribution. Benefits of the SaaS model include:<ul><li>easier administration</li><li>automatic updates and patch management</li><li>compatibility: All users will have the same version of software.</li><li>easier collaboration, for the same reason</li><li>global accessibility</li></ul>The traditional model of software distribution, in which software is purchased for and installed on personal computers, is sometimes referred to as software as a product.|http://searchcloudcomputing.techtarget.com/definition/Software-as-a-Service",
        "PaaS":      "Platform as a Service|A cloud model in which providers deliver apps over the Internet and host users' hardware and software on their infrastructure. In a PaaS model, a cloud provider delivers hardware and software tools -- usually those needed for application development -- to its users as a service. A PaaS provider hosts the hardware and software on its own infrastructure. As a result, PaaS frees users from having to install in-house hardware and software to develop or run a new application. PaaS does not typically replace a business' entire infrastructure. Instead, a business relies on PaaS providers for key services, such as Java development or application hosting. For example, deploying a typical business tool locally might require an IT team to buy and install hardware, operating systems, middleware (such as databases, Web servers and so on) the actual application, define user access or security, and then add the application to existing systems management or application performance monitoring (APM) tools. IT teams must then maintain all of these resources over time. A PaaS provider, however, supports all the underlying computing and software; users only need to log in and start using the platform – usually through a Web browser interface.<br>Most PaaS platforms are geared toward software development, and they offer developers several advantages. For example, PaaS allows developers to frequently change or upgrade operating system features. It also helps development teams collaborate on projects.|http://searchcloudcomputing.techtarget.com/definition/Platform-as-a-Service-PaaS",
        "LaaS":      "Lighting as a Service|A service delivery model in which light service is charged on a subscription basis rather than via a one-time payment. This business model has become more common in commercial and citywide installations of LED lights, specifically in retrofitting buildings and outdoor facilities, with the aim of reducing installation costs. Light vendors have used an LaaS strategy in selling value-added services, such as Internet-connected lighting and energy management.<br>A notable example of an LaaS model is the Philips and Ericsson partnership that complements Philips' LED street lights with Ericsson's small cell small telecom equipment in urban areas.<br>Cisco LaaS (Light as a Service) is a two-year innovation project co-funded by the UK's innovation agency, Innovate UK. LaaS will bring to market lighting that is powered, connected and controlled by digital networks. This will create vast capabilities to manage smart loads, reduce costs and carbon emissions, and create new use cases for lighting. LaaS will open a new spectrum of digital innovation and change the way we think about light.<br>LaaS will be a testbed to demonstrate the Internet of Things for power networks in commercial building management. As part of the project, we will develop and integrate protocols, test them in hardware devices and demonstrate the solution in a live environment. The technology will be self-aware and open to new devices and applications, allowing for open innovation that includes major industry players as well as cutting-edge SMEs.|http://en.wikipedia.org/wiki/Lighting_as_a_service|Wiki",
        "User Story": "User Story|In software development and product management, a user story is a description consisting of one or more sentences in the everyday or business language of the end user or user of a system that captures what a user does or needs to do as part of his or her job function. User stories are used with agile software development methodologies as the basis for defining the functions a business system must provide, and to facilitate requirements management. It captures the 'who', 'what' and 'why' of a requirement in a simple, concise way, often limited in detail by what can be hand-written on a small paper notecard.|http://en.wikipedia.org/wiki/User_story|Wiki",
        "IoT":       "Internet of Things|The network of physical objects or \"things\" embedded with electronics, software, sensors and connectivity to enable it to achieve greater value and service by exchanging data with the manufacturer, operator and/or other connected devices. Each thing is uniquely identifiable through its embedded computing system but is able to interoperate within the existing Internet infrastructure.|http://en.wikipedia.org/wiki/Internet_of_Things|Wiki",
        "IoE":       "Internet of Everything|The network of physical objects or \"things\" embedded with electronics, software, sensors and connectivity to enable it to achieve greater value and service by exchanging data with the manufacturer, operator and/or other connected devices. Each thing is uniquely identifiable through its embedded computing system but is able to interoperate within the existing Internet infrastructure.|http://en.wikipedia.org/wiki/Internet_of_Things|Wiki",
        "B2B":       "Business-To-Business|Commerce transactions between businesses, such as between a manufacturer and a wholesaler, or between a wholesaler and a retailer. Contrasting terms are business-to-consumer (B2C) and business-to-government (B2G). B2B branding is a term used in marketing.|http://en.wikipedia.org/wiki/Business-to-business|Wiki",
        "M2M":       "Machine-To-Machine|Refers to technologies that allow both wireless and wired systems to communicate with other devices of the same type. M2M is a broad term as it does not pinpoint specific wireless or wired networking, information and communications technology. This broad term is particularly used by business executives. M2M is considered an integral part of the Internet of Things (<div class='inlink'>IoT</div>) and brings several benefits to industry and business in general as it has a wide range of applications such as industrial automation, logistics, Smart Grid, Smart Cities, health, defense etc. mostly for monitoring but also for control purposes.<br>In order to support the rapid new development and the worldwide adoption of the Internet of Things as well as the continued growth of M2M technology and its large scale applications in the future, a global adoption and deployment of the Internet Protocol Version 6 (IPv6) are required because all of the sensors and machine-readable identifiers needed to make the Internet of Things a reality will need an extremely large address space. Even if the current supply of IPv4 addresses were not to be exhausted soon, the size of IPv4 itself is not large enough to support the future requirement of IoT.<br>Consequently, the future success of M2M, as an integral part of the IoT, will largely be determined by the successful global adoption of IPv6.<br>M2M can include the case of industrial instrumentation - comprising a device (such as a sensor or meter) to capture an event (such as temperature, inventory level, etc.) that is relayed through a network (wireless, wired or hybrid) to an application (software program) that translates the captured event into meaningful information (for example, items need to be restocked). Such communication was originally accomplished by having a remote network of machines relay information back to a central hub for analysis, which would then be rerouted into a system like a personal computer.<br>However, modern M2M communication has expanded beyond a one-to-one connection and changed into a system of networks that transmits data to personal appliances. The expansion of IP networks across the world has made it far easier for M2M communication to take place and has lessened the amount of power and time necessary for information to be communicated between machines. These networks also allow an array of new business opportunities and connections between consumers and producers in terms of the products being sold.|http://en.wikipedia.org/wiki/Machine_to_machine|Wiki",
        "IT":        "Information Technology|The application of computers and telecommunications equipment to store, retrieve, transmit and manipulate data, often in the context of a business or other enterprise.<br>The term is commonly used as a synonym for computers and computer networks, but it also encompasses other information distribution technologies such as television and telephones. Several industries are associated with information technology, including computer hardware, software, electronics, semiconductors, internet, telecom equipment, e-commerce and computer services.|http://en.wikipedia.org/wiki/Information_technology|Wiki",
        "JSON":      "JavaScript Object Notation|An open standard format that uses human-readable text to transmit data objects consisting of attribute-value pairs. It is used primarily to transmit data between a server and web application, as an alternative to XML.<br>Although originally derived from the JavaScript scripting language, JSON is a language-independent data format. Code for parsing and generating JSON data is readily available in many programming languages.|http://en.wikipedia.org/wiki/JSON|Wiki",
        "SMBs":      "Small and Medium-Sized Businesses|In the United States, the Small Business Administration sets small business criteria based on industry, ownership structure, revenue and number of employees (which in some circumstances may be as high as 1500, although the cap is typically 500).|http://en.wikipedia.org/wiki/Small_and_medium-sized_enterprises|Wiki",
        "ETL":       "Extract, Transform, and Load|In computing, Extract, Transform and Load (ETL) refers to a process in database usage and especially in data warehousing that:<ul><li>Extracts data from homogeneous or heterogeneous data sources</li><li>Transforms the data for storing it in proper format or structure for querying and analysis purpose</li><li>Loads it into the final target (database, more specifically, operational data store, data mart, or data warehouse)</li></ul>Usually all the three phases execute in parallel since the data extraction takes time, so while the data is being pulled another transformation process executes, processing the already received data and prepares the data for loading and as soon as there is some data ready to be loaded into the target, the data loading kicks off without waiting for the completion of the previous phases.<br>ETL systems commonly integrate data from multiple applications (systems), typically developed and supported by different vendors or hosted on separate computer hardware. The disparate systems containing the original data are frequently managed and operated by different employees. For example a cost accounting system may combine data from payroll, sales and purchasing.|http://en.wikipedia.org/wiki/Extract,_transform,_load|Wiki",
        "Fog Computing":"Fog Computing|Fog computing or fog networking is an architecture that uses one or a collaborative multitude of end-user clients or near-user edge devices to carry out a substantial amount of storage (rather than stored primarily in cloud data centers), communication (rather than routed over the internet backbone), and control, configuration, measurement and management (rather than controlled primarily by network gateways such as those in the LTE (telecommunication) core).<br>Fog Networking consists of a control plane and a data plane. For example, on the data plane, fog computing enables computing services reside at the edge of the network as opposed to servers in a data-center. Compared to cloud computing, fog computing emphasizes proximity to end-users and client objectives, dense geographical distribution and local resource pooling, latency reduction for quality of service (QoS) and edge analytics/stream mining, resulting in superior user-experience and redundancy in case of failure.<br>Fog Networking supports the Internet of Everything (<div class='inlink'>IoE</div>), in which most of the devices that we use on a daily basis will be connected to each other. Examples include our phones, wearable health monitoring devices, connected vehicle and augmented reality using devices such as the Google Glass.|http://en.wikipedia.org/wiki/Fog_computing|Wiki",
        "Edge Computing":"Edge Computing|Edge Computing is pushing the frontier of computing applications, data, and services away from centralized nodes to the logical extremes of a network. It enables analytics and knowledge generation to occur at the source of the data. This approach requires leveraging resources that may not be continuously connected to a network such as laptops, smartphones, tablets and sensors. Edge Computing covers a wide range of technologies including wireless sensor networks, mobile data acquisition, mobile signature analysis, cooperative distributed peer-to-peer ad hoc networking and processing also classifiable as Local Cloud/Fog computing and Grid/Mesh Computing, distributed data storage and retrieval, autonomic self-healing networks, virtual cloudlets, remote cloud services, augmented reality, and more.|http://en.wikipedia.org/wiki/Edge_computing|Wiki",
        "Inrix":     "Inrix|At the Intersection of Connecting Cars to Smarter Cities: For over 10 years, our business has been traffic. We have over 50 patents related to traffic and transportation. Today we help governments tap into Big Data and the Internet of Things to engineer systems for Smart Cities that go beyond traffic to address the individual, economic and environmental challenges of urbanization worldwide.|http://inrix.com/|Company Website",
        "CI":        "Continuous Integration|The practice, in software engineering, of merging all developer working copies with a shared mainline several times a day. It was adopted as part of extreme programming (XP), which did advocate integrating more than once per day, perhaps as many as tens of times per day. The main aim of CI is to prevent integration problems, referred to as \"integration hell\" in early descriptions of XP. CI isn't universally accepted as an improvement over frequent integration, so it is important to distinguish between the two as there is disagreement about the virtues of each.<br>In addition to automated unit tests, organisations using CI typically use a build server to implement <i>continuous</i> processes of applying quality control in general — small pieces of effort, applied frequently. In addition to running the unit and integration tests, such processes run additional static and dynamic tests, measure and profile performance, extract and format documentation from the source code and facilitate manual QA processes. This continuous application of quality control aims to improve the quality of software, and to reduce the time taken to deliver it, by replacing the traditional practice of applying quality control after completing all development. This is very similar to the original idea of integrating more frequently to make integration easier, only applied to QA processes.<br>In the same vein, the practice of continuous delivery further extends CI by making sure the software checked in on the mainline is always in a state that can be deployed to users and makes the actual deployment process very rapid.|http://en.wikipedia.org/wiki/Continuous_integration|Wiki",
        "CD":        "Continuous Delivery|Also called Continuous Deployment. Continuous Delivery is a software engineering approach in which teams keep producing valuable software in short cycles and ensure that the software can be reliably released at any time. It is used in software development to automate and improve the process of software delivery. Techniques such as automated testing and continuous integration (<div class='inlink'>CI</div>) allow software to be developed to a high standard and easily packaged and deployed to test environments, resulting in the ability to rapidly, reliably and repeatedly push out enhancements and bug fixes to customers at low risk and with minimal manual overhead. CD builds on CI by adding the regular deployments to production as part of the process, however CD is not a requirement of CI. The technique (CD) was one of the assumptions of extreme programming but at an enterprise level has developed into a discipline of its own, with job descriptions for roles such as \"buildmaster\" calling for CD skills as mandatory.|http://en.wikipedia.org/wiki/Continuous_delivery|Wiki",
        "OEM":       "Original Equipment Manufacturer|Original equipment manufacturer (OEM) is a term used when one company makes a part or subsystem that is used in another company's end product. The term is used in several ways, each of which is clear within a context. The term sometimes refers to a part or subassembly maker, sometimes to a final assembly maker, and sometimes to a mental category comprising those two in contrast to all other third-party makers of parts or subassemblies from the aftermarket.<br>In the first usage, the OEM is the company that makes a part that is marketed by another company, typically as a component of the second company's own product. For example, if Acme Manufacturing Co. makes power cords that are used on IBM computers, Acme is regarded as the OEM of the power cords.<br>In the second usage, OEM refers to companies like value-added resellers, which are the second manufacturer in the definition above. If, for example, Hewlett-Packard sells circuit boards to Acme Systems for use in Acme's security systems, HP refers to Acme as an OEM.<br>In the third usage, OEM is a mental category for all of the makers involved when a final assembly was first built (originally equipped)—in contrast to whoever made aftermarket parts that were installed later. For example, if Ford used Autolite spark plugs, Exide batteries, Bosch fuel injectors, and Ford's own engine blocks and heads when building a car, then car restorers and collectors consider all of those brands as OEM brands, in contrast to aftermarket brands (such as Champion plugs, DieHard batteries, Kinsler fuel injectors, and BMP engine blocks and heads). This can mean that Bosch injectors are considered OEM parts on one car model and aftermarket parts on another model.|http://en.wikipedia.org/wiki/Original_equipment_manufacturer|Wiki",
        "SI":        "Systems Integrator|A systems integrator is a person or company that specializes in bringing together component subsystems into a whole and ensuring that those subsystems function together, a practice known as system integration. Systems integrators may work in many fields but the term is generally used in the information technology (<div class='inlink'>IT</div>) field, the defense industry, or in media.<br>According to the Institute for Partner Education & Development, systems integrators traditionally realize approximately 50 percent of revenue from consulting services and 40 percent of revenue from IT services in design, implementation and post-transaction consulting. They are different from an IT Consultant in that they also take title to product.|http://en.wikipedia.org/wiki/Systems_integrator|Wiki",
        "PAK":       "Product Activation Key|A product key, also known as a software key, is a specific software-based key for a computer program. It certifies that the copy of the program is original. Activation is sometimes done offline by entering the key, or with software like Windows 8.1, online activation is required to prevent multiple people using the same key. Not all software has a product key, as some publishers may choose to use a different method to protect their copyright, or in some cases, such as open source software, copyright protection is not used.<br>Computer games use product keys to verify that the game has not been illegally copied. Likewise, one is not allowed to play online with two identical product keys at the same time.<br>Product keys consist of a series of numbers and/or letters. This sequence is typically entered by the user during the installation of computer software, and is then passed to a verification function in the program. This function manipulates the key sequence according to a mathematical algorithm and attempts to match the results to a set of valid solutions.|http://en.wikipedia.org/wiki/Product_key|Wiki",
        "CDP":       "City Digital Platform|See <div class='inlink'>CIM</div>.",
        "E2E":       "End to End|",
        "MP":        "Marketplace|",
        "IE2K":      "Industrial Ethernet 2000 Series Switches|",
        "CDC":       "City Data Center|",
        "SDP":       "Software Defined Platform|",
        "VSN":       "Virtual Service Node|",
        "SBP":       "Subscription Billing Platform|",
        // "CPD":       "Control Point Discovery|?",
        // "CLD":       "?|?",
        // "IS":        "?|?",
        // "SI":        "Standard Image|?",

        "TDL":       "Thing Definition Language|The purpose of the Model definition language is to define higher level models that can be accessed from Thing Queries. Model definitions can be thought of as external interfaces to the lowel-level thing facet scripts. Model definitons are also required to store the data that is received from things or other non-things storage.",
        "TIL":       "Thing Interaction Language|Thing Query Language (<div class='inlink'>TQL</div>) is yet another atomic language that is specifically designed around providing direct access for end applications to thing (or non-thing) related models and allowing users to take actions, with orthogonal applicable policices.",
        "WDL":       "Workflow Definition Language|In the context of Atomic language specification, Workflow definition is the automation of a device interaction and associated process (logic), in whole or part. Information or tasks are passed from one participant to another for action, according to a set of procedural rules. It consists of a numbers of logical steps, each of which is knows as an Task.",
        "TQL":       "Thing Query Language|An <div class='inlink'>IoT</div> Application Platform that creates queriable and actionable systems of interconnected things. Using TQL, IoT application developers can easily implement interactive and responsive IoT business logic using TQL statements.",
        "DSL":       "Domain-Specific Language|A computer language specialized to a particular application domain. There is a wide variety of DSLs, ranging from widely used languages for common domains, such as HTML for web pages, down to languages used by only a single piece of software. DSLs can be further subdivided by the kind of language, and include domain-specific <i>markup</i> languages, domain-specific <i>modeling languages</i> (more generally, specification languages), and domain-specific <i>programming languages</i>. Special-purpose computer languages have always existed in the computer age, but the term \"domain-specific language\" has become more popular due to the rise of domain-specific modeling.|http://en.wikipedia.org/wiki/Domain-specific_language|Wiki",
        "DSM":       "Domain-Specific Modeling|A software engineering methodology for designing and developing systems, most often <div class='inlink'>IT</div> systems such as computer software. It involves systematic use of a graphical domain-specific language (<div class='inlink'>DSL</div>) to represent the various facets of a system. DSM languages tend to support higher-level abstractions than General-purpose modeling languages, so they require less effort and fewer low-level details to specify a given system.|http://en.wikipedia.org/wiki/Domain-specific_modeling|Wiki",
        "GPL":       "General-Purpose Language|A computer language broadly applicable across domains, and lacks specialized features for a particular domain.",



        "Sandbox":   "Sandbox|A sandbox is a testing environment that isolates untested code changes and outright experimentation from the production environment or repository, in the context of software development including Web development and revision control. Sandboxing protects \"live\" servers and their data, vetted source code distributions, and other collections of code, data and/or content, proprietary or public, from changes that could be damaging (regardless of the intent of the author of those changes) to a mission-critical system or which could simply be difficult to revert. Sandboxes replicate at least the minimal functionality needed to accurately test the programs or other code under development (e.g. usage of the same environment variables as, or access to an identical database to that used by, the stable prior implementation intended to be modified; there are many other possibilities, as the specific functionality needs vary widely with the nature of the code and the application[s] for which it is intended.<br>The concept of the sandbox (sometimes also called a working directory, a test server or development server) is typically built into revision control software such as CVS and Subversion (SVN), in which developers \"check out\" a copy of the source code tree, or a branch thereof, to examine and work on. Only after the developer has (hopefully) fully tested the code changes in their own sandbox should the changes be checked back into and merged with the repository and thereby made available to other developers or end users of the software.<br>By further analogy, the term \"sandbox\" can also be applied in computing and networking to other temporary or indefinite isolation areas, such as security sandboxes and search engine sandboxes (both of which have highly specific meanings), that prevent incoming data from affecting a \"live\" system (or aspects thereof) unless/until defined requirements or criteria have been met.|http://en.wikipedia.org/wiki/Sandbox_(software_development)|Wiki",
        "Agile Development":"Agile Software Development|A group of software development methods in which requirements and solutions evolve through collaboration between self-organizing, cross-functional teams. It promotes adaptive planning, evolutionary development, early delivery, continuous improvement, and encourages rapid and flexible response to change.|http://en.wikipedia.org/wiki/Agile_software_development|Wiki",
        "DT":        "Deutsche Telekom|A German telecommunications company headquartered in Bonn. Deutsche Telekom was formed in 1996 as the former state-owned monopoly Deutsche Bundespost was privatized. As of June 2008, the German government still holds a 15% stake in company stock directly, and another 17% through the government bank KfW.|http://en.wikipedia.org/wiki/Deutsche_Telekom|Wiki",
        "TDC":       "Tele Danmark Communications|TDC A/S (formerly Tele Danmark) is a Danish telecommunications company dating back to 1879. As of today, TDC is the largest telephone company in Denmark with approx. 8.9 million customer relations (2010) within telephony, broadband, and television. The company's headquarters are located on Teglholmsgade in Copenhagen. Even though the Danish home market is the primary focus of business, TDC is also represented as a market challenger in Norway, Sweden, and Finland through the business unit TDC Nordic.|http://en.wikipedia.org/wiki/TDC_A/S|Wiki",
        "AGT":       "AGT International|Privately-held company headquartered in Switzerland, <div class='inlink'>IoT</div> Analytics platform. We apply our IoT analytics to the new wave of IoT data to uncover the patterns and relationships that lead to fresh business insights - insights that create new efficiencies, generate new revenue streams and improve corporate profitability. IoT analytics that will help businesses to create more innovative products and deliver them more efficiently. And enable cities to deliver new services and engage more effectively with citizens. As the premier supplier of specialized IoT analytics and a global IoT pioneer and leader AGT International is solving real-world problems for businesses and governments all over the world including smart cities, water infrastructure management, energy management, traffic management, critical asset management and large-scale event management.|https://www.agtinternational.com/|Company Website",
        "TCS":       "Tata Consultancy Services|Tata Consultancy Services (TCS) is a global leader in <div class='inlink'>IT</div> services, digital and business solutions that partners with its clients to simplify, strengthen and transform their businesses. We ensure the highest levels of certainty and satisfaction through a deep-set commitment to our clients, comprehensive industry expertise and a global network of innovation and delivery centers.|http://www.tcs.com/Pages/default.aspx|Company Website",
        "PLAT.ONE":  "PLAT.ONE|PLAT.ONE is a renowned developer of enterprise-grade software and industrial solutions. Since its release in 2011, PLAT.ONE has established itself as the platform of choice for connected applications in major Telecoms, System Integrators and global industrial equipment companies. PLAT.ONE’s distributed architecture, integrated development and deployment features, and native security and data-aware operations reduce application development time while providing Enterprise-Grade, non-stop operations. Businesses use PLAT.ONE to deploy innovative connected solutions ranging from smart equipment and transportation to smart cities and manufacturing.|http://www.plat.one/|Company Website",
        "WorldSensing":"Worldsensing|Worldsensing, founded in 2008 in Barcelona, and based in London and Barcelona, has become a market leader in innovative wireless machine-to-machine (<div class='inlink'>M2M</div>) and Internet-of-Things (<div class='inlink'>IoT</div>) technologies. Worldsensing is structured into two divisions:<ol><li>Worldsensing Industrial - which offers wireless monitoring solutions for civil infrastructures, is deploying Loadsensing, which offers a wide range of solutions to digitise almost all geotechnical sensors available on the market, and launching Spidernano, one of the world's most advanced wireless seismic acquisition systems.</li><li>Worldsensing Traffic - which holds a unique traffic management portfolio for Smart Cities that includes Bitcarrier, a real-time intelligent traffic management and information solution designed for both road and urban environments, and its intelligent parking system Fastprk.</li>|http://www.worldsensing.com/|Company Website",
        "Sensity":   "Sensity|Sensity Systems capitalizes on conversions to LED lighting—a process that will affect 4 billion lights worldwide over the next few years - to create a high-speed, sensor-based, multiservice, open networking platform known as a Light Sensory Network (LSN). LSNs help lighting owners improve lighting control and energy efficiency, as well as business processes that go well beyond lighting.<br>By embedding networking technology and sensors within LED luminaires themselves, Sensity uses energy-efficient LED lighting as the foundation for its turnkey NetSense platform, the first Light Sensory Network implementation. By working closely with developers of software applications and services that run on the NetSense platform, Sensity enables facility and municipal lighting owners to link energy efficiency and cost savings to the improvement of business goals as diverse as public safety, parking control, asset management, and retail analytics.|http://www.sensity.com/|Company Website",
        "Acuity":    "Acuity Brands|Acuity Brands, Inc. is a North American market leader and one of the world's leading providers of lighting solutions for both indoor and outdoor applications. With fiscal year 2014 net sales of over $2.4 billion, Acuity Brands employs approximately 7,000 associates and is headquartered in Atlanta, Georgia, with operations throughout North America, and in Europe and Asia.<br>Our innovative lighting solutions cover both conventional fixtures and advanced solid-state technology that can seamlessly integrate with powerful digital controls and daylighting to create greater energy efficiencies and a higher quality of light.<br>Our century of tradition, our current financial strength and our commitment to a sustainable future, ensure our ability to grow, innovate and further capture the rapidly growing market opportunities before us.|http://www.acuitybrands.com/|Company Website",
        "Altiux":    "Altiux Innovations|Altiux Innovations is a product engineering, design and technology services company that helps clients to design, develop and deploy products and solutions for the connected world. With expertise in <div class='inlink'>M2M</div>, <div class='inlink'>IoT</div>, Mobility, Big data, Cloud and Analytics we help build products and solutions for companies in the Consumer Electronics, Homes, Intelligent Buildings, Smart Cities and Manufacturing verticals.<br>Our deep domain expertise along with our platform agnostic IoT solution accelerators helps our clients develop differentiated products while accelerating time-to-market and reducing overall product development expenses. Our vision is to play a key role in shaping technologies of tomorrow, today through our innovation and product engineering capabilities. Our mission is to be the number one product engineering services company for a smarter connected world.|http://www.altiux.com/|Company Website",
        "Atomiton":  "Atomiton|<div class='inlink'>TQL</div> (Thing Query Language) is an <div class='inlink'>IoT</div> Application Platform that creates queriable and actionable systems of interconnected things. Using TQL, IoT application developers can easily implement interactive and responsive IoT business logic using TQL Statements.|http://atomiton.com/|Company Website",
        "Aptus":     "Aptus|The Framework integrates existing services and backend applications into a next-generation, consumer-grade UI. Thanks to platform-agnostic HTML5, the UI is built for both web and mobile at the same time. The Framework includes and interfaces with components common to most enterprise applications. This makes customization easy - and dramatically shortens your time to market.|http://mtuity.com/|Company Website (Mtuity)",
        "ICE Gateway":"ICE Gateway|Our wireless infrastructure (<div class='inlink'>IaaS</div>: Infrastructure as a Service) optimizes the outdoor lighting and adds many value added services for people passing by lights and also for sensors and devices (<div class='inlink'>IoT</div>: Internet of Things) in smart cities. ICE turns the streetlights to a high bandwidth (3G) infrastructure for outdoor lighting, traffic, real time marketing, security and logistic. Our customers have no additional efforts and hidden costs. You do not need any ISP (Internet Service Provider) or new telecommunication contracts, and will be in the position to use the ICE IaaS in combination with your preferred suppliers for lights, devices, applications and sensors.|http://www.ice-gateway.com/index.php?lang=en|Company Website",
        "Bajaj":     "Bajaj Electricals|An Indian consumer electrical equipments manufacturing company based in Mumbai, Maharashtra. It is a part of the Rs. 380 billion (US $6.0 billion) Bajaj Group. It has diversified with interests in lighting, luminaries, appliances, fans, LPG based Generators, engineering and projects. Its main domains are lighting, consumer durables, engineering and projects. Lighting includes lamps, tubes and luminaires. Consumer durables include appliances and fans. Engineering and projects include transmission line towers, telecommunications towers, highmast, poles and special projects, and others include die casting, wind energy & solar energy. Some notable project includes lighting works at the Commonwealth Games stadium and the Bandra Worli Sea Link.|http://bajajelectricals.com/|Company Website",
        "Sensys":    "Sensys Networks|As a leading wireless technology company, Sensys Networks provides traffic visionaries and implementers with a comprehensive data solution. Our suite of products and traffic management solutions, together with its esteemed list of integration partners, helps drive efficient, economic and environmental improvements for cities.|http://sensysnetworks.com/|Company Website"
    };

    acronyms = Object.keys(definitions).sort();

    for (var i = 0; i < acronyms.length; i++) {
        var acr = acronyms[i];
        var sep = definitions[acr].split("|");
        var name = sep[0], desc = sep[1];
        var link_address = sep[2], link_name = sep[3] ? sep[3] : "More Info";
        var link = link_address ?
            "<a href='"+link_address+"' target='_blank'>"+link_name+"</a>"
            : "";

        $("#results").text(acronyms.length + " results");

        $("#output").append(
            "<div class='container'><div class='acronym'>"
            +acr+"</div><div class='definition'><div class='title'>"
            +name+"</div><div class='link'>"+link+"</div><div class='description'>"
            +desc+"</div></div></div>");
    };
    
    $("div#output").on("click", "div.inlink", function(){
        $("html, body").animate({
            scrollTop: "0px"
        }, "fast");
        $("#input").val($(this).text());
        query();
        $("#input").focus();
    });
    
    function query(){
        first = null;
        $("#output").empty();
        var q = $("#input").val();
        var regex = new RegExp(
            q.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&"), "i");
        var acr_matches = $.grep(acronyms, function(n, i){
            return n.match(regex) != null;
        });
        var title_matches = $.grep(acronyms, function(n, i){
            return definitions[n].split("|")[0].match(regex) != null
                && n.match(regex) == null;
        });
        var desc_matches = $.grep(acronyms, function(n, i){
            return definitions[n].split("|")[1].replace(/<.+?>/g," ")
                .match(regex) != null && n.match(regex) == null
                && definitions[n].split("|")[0].match(regex) == null;
        });

        var numResults = acr_matches.length + title_matches.length
                         + desc_matches.length
        var resString = (numResults == 1) ? " result" : " results"
        $("#results").text(numResults + resString);

        if (numResults == 0) {
            $("#output").append("<a class='search' target='_blank' href='http://en.wikipedia.org/w/index.php?search=" + q + "'>Search Wikipedia for \""+q+"\"?</a><a class='search' target='_blank' href='https://www.google.com/search?q="+q+"'>Search Google for \""+q+"\"?</a>");
        };

        highlightAndAppend(acr_matches, q, regex, "acr");
        highlightAndAppend(title_matches, q, regex, "title");
        highlightAndAppend(desc_matches, q, regex, "desc");
    };

    $("#input").keyup(function(e){
        if (e.keyCode != 13 && e.keyCode != 16) {
            query();
        };
    });

    function highlightAndAppend(matches, q, regex, s) {
        for (var i = 0; i < matches.length; i++) {
            var acr = matches[i];
            var sep = definitions[acr].split("|");
            var title = sep[0], desc = sep[1];
            var link_address = sep[2], link_name = sep[3] ? sep[3] : "More Info";

            switch(s) {
                case "acr":
                    acr = highlight(regex, acr, q);
                    break;
                case "title":
                    title = highlight(regex, title, q);
                    break;
                case "desc":
                    desc = highlight(regex, desc, q);
                    break;
            }

            append(acr, title, link_address, link_name, desc);
        };
    };

    function highlight(regex, part, q) {
        var j = regex.exec(part).index;
        return part.slice(0, j) + "<div class='highlight'>"
            + part.slice(j, j + q.length)
            + "</div>" + part.slice(j + q.length);
    }

    function append(acr, title, link_address, link_name, desc) {
        var link = link_address ?
            "<a href='"+link_address+"' target='_blank'>"+link_name+"</a>"
            : "";

        $("#output").append(
            "<div class='container'><div class='acronym'>"
            +acr+"</div><div class='definition'><div class='title'>"
            +title+"</div><div class='link'>"+link+"</div><div class='description'>"
            +desc+"</div></div></div>");
    };

    var first = null;

    $("#input").keydown(function(e){
        if (e.keyCode == 13) {
            if (!e.shiftKey && first && first.is(".container:last-child")
                || e.shiftKey && !first) {
                return;
            } else if (!e.shiftKey && !first) {
                first = $(".container:first-child");
            } else if (!e.shiftKey) {
                first = first.next();
            } else if (e.shiftKey && first.is(".container:first-child")) {
                first = null;
            } else if (e.shiftKey) {
                first = first.prev();
            };
            var offset = first ? first.offset().top : 0;
            $("html, body").animate({
                scrollTop: offset + "px"
            }, "fast");
        };
    });

});
